export const DRAWER_TOGGLE = 'DRAWER_TOGGLE';

export const SETTINGS_UPDATE_TOKEN = 'SETTINGS_UPDATE_TOKEN';
export const SETTINGS_TOGGLE = 'SETTINGS_TOGGLE';

export const SETTINGS_PREFERENCES_REQUEST = 'SETTINGS_PREFERENCES_REQUEST';
export const SETTINGS_PREFERENCES_RESPONSE = 'SETTINGS_PREFERENCES_RESPONSE';
export const SETTINGS_PREFERENCES_SAVE_REQUEST = 'SETTINGS_PREFERENCES_SAVE_REQUEST';
export const SETTINGS_PREFERENCES_SAVE_RESPONSE = 'SETTINGS_PREFERENCES_SAVE_RESPONSE';
export const SETTINGS_TAB = 'SETTINGS_TAB';

export const QUERY_UPDATE_LANGUAGE = 'QUERY_UPDATE_LANGUAGE';
export const QUERY_UPDATE_USERNAME = 'QUERY_UPDATE_USERNAME';
export const QUERY_UPDATE_REPO = 'QUERY_UPDATE_REPO';
export const QUERY_UPDATE_REPO_QUERY = 'QUERY_UPDATE_REPO_QUERY';
export const QUERY_UPDATE_ORGANIZATION = 'QUERY_UPDATE_ORGANIZATION';
export const QUERY_UPDATE_USER = 'QUERY_UPDATE_USER';
export const QUERY_SEARCH = 'QUERY_SEARCH';

export const WEBSOCKET_CONNECTED = 'WEBSOCKET_CONNECTED';
export const WEBSOCKET_DISCONNECTED = 'WEBSOCKET_DISCONNECTED';

export const LOG_START = 'LOG_START';
export const LOG_STOP = 'LOG_STOP';
export const LOG_RATE_EXCEEDED = 'LOG_RATE_EXCEEDED';
export const LOG_UNAUTHORIZED = 'LOG_UNAUTHORIZED';
export const LOG_NOT_FOUND = 'LOG_NOT_FOUND';
export const LOG_RATE_LIMIT = 'LOG_RATE_LIMIT';
